### PR TITLE
Tidy up no-python refactor

### PR DESCRIPTION
**Pull request by mvahowe**
Despite the branch name, this PR does not change much regarding page sizes. Instead, there's a lot of technical debt reduction and general tidying including
- Making fuller use of the CLI library to provide extensive argument checking
- a verbose flag, plus more verbose verbose output
- working data in a working directory, the default location of which is `~/.jxlpdf/working`
- options to produce just the individual PDFs, or just assemble existing those PDFs, or both which, together with a choice of working directory, allows flexible testing without evil code hacking
- renamed functions and variables
- `forceQuit` and `forceSkip` options for sections in config file, to make debugging a little more fun

`node scripts/make_pdf.js -c config/fr/kitchen_sink.json -o ~/Documents/kitchen_sink.pdf -v`

to try most of the options. This should fail meaningfully if you run it a second time. Then add -f and try
- `-s ASSEMBLE`
- `-s CLEAR`
- `-s ASSEMBLE` (should fail meaningfully)
- `-s ORIGINATE` (yes it's a real word : https://www.proactive.marketing/glossary/origination/ )

### CODE REVIEW

**Comment by mvahowe** [comment]
@DanielC-N Wait, why do we have the whole of pdf-lib in our repo?

**Comment by DanielC-N** [comment]
@mvahowe It was for tests 2 weeks ago, I forgot to remove it.

**Comment by DanielC-N** [comment]
unexpected behavior :
- first run `node scripts/make_pdf.js -c config/fr/kitchen_sink.json -o ~/Documents/kitchen_sink.pdf`
- then run `node scripts/make_pdf.js -c config/fr/short.json -o ./testingCommand.pdf -s ASSEMBLE`

It will assemble the pdf with the previous config.  
Maybe we could check the called config file and the previously generated manifest to fix this?

**Comment by mvahowe** [comment]
We could but anyone doing this should know what they are doing, since the only reason to do it is debugging.

**Comment by DanielC-N** [comment]
I've made some changes to improve the readability of the code. And added some comments.
- `cli-parser.js` : now handle the options logic
- `constants.js` : self explanatory
- `validators.js`: the validation logic for the options

now `make_pdf.js` only calls this :
```js
const parseCommandLineArguments = require('./cli-parser');

const options = parseCommandLineArguments();
```

**Comment by mvahowe** [comment]
This looks good!

Can we define all variables explicitly and in the smallest possible scope? ie
```
    let startOn = manifestStep.startOn;
    for (let i = 1; i < manifestStep.numPages; i++) {
        const currentPage = manifestStep.pdf.getPage(i);
        startOn = startOn === "recto" ? "verso" : "recto";
        ...
    }
    manifestStep.pdf.save();
```
becomes
```
let currentPage;
    let startOn = manifestStep.startOn;
    for (let i = 1; i < manifestStep.numPages; i++) {
        currentPage = manifestStep.pdf.getPage(i);
        startOn = startOn === "recto" ? "verso" : "recto";
        ...
    }
    manifestStep.pdf.save();
```

**Comment by mvahowe** [comment]
Also, we now have four files in the `scripts` directory, three of which are not scripts. I suggest adding a `helpers` subdirectory.

**Review by DanielC-N — APPROVED** [review]

**Pull request merged**
